language: python
python:
  - 3.6
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - echo 'DATABASE_URL=sqlite:///db.sqlite3' > .env
script:
  - python manage.py migrate
  - python manage.py test
